sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- echo "This design module has no tests"
after_success:
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: LnlgnMBb+4j3Q53+hVJJIme9X6wWvEt05SZMwHVeXzTL7YMLKjEDS/V+flspKaK2kQvdh2hvfKWvyajsf7Vp/ISVoOpTnJIZ9aBehfNFGRv5vbzpBKikQQwG5KD1G9diZ/haCNecSEDu91IO2VBv7eUsxn214/RZVIW2zaeDgOqypMRaVh5V5E7znKaXpUJLabbLRBkLfKaeSO5UUtmfM7Rcx09a8pzkO4QlSnVFE0auSjfCRHgMetCBmdWVQHyp35D9WNVo0e2WDmx3F2xlk0kiphxSaxIqsVrbDsS5ZsRvN2mMm8iH6Y6RUZS0X26D0YfUaEMeORQjEaCTvQTG1gynwz4Gt3LhhTSjZ3hw6dyr0Nb464t/vcfwUFYBj5bFACw9AEWh1wNuro1+lQbOv6n3aD6A1yZF8Ok4S6KoHFFZ9ShwOYWNQHsh5pgDIR3qrfjifgUJRUVVBPBKQOBtpNX5squVRRbiLTUc8atljBGlMb6HLqGheEpr0jRZaPwOIKUqTjJ81Wc9kJpwM9o3YdmaJGhOXHiLgJ5X40yEl9m94b5TZNTEMhtbMoaX4K2YccOoVsTIU9gsIDydBOV7KnuuSg1sPPi4dFGNQPV0qbG1BBA0rcfBHrn5zL7twAdBGIwCCfLYFqC1sbe7spEimfNPMzGzI6XS4uRfDuTUNI4=
  - secure: cFWqPHOZACW5jNMJu78XB1lFNIoEVN69wxoaJKBPJJTB/IfeHXZVMXmlokqdFJGZs7xpSUEVX8Mh+xqradUtzKr5f9hjejOBX81VOQgwAJffeiAnqcDCtG8cBIOlFgh4sg/6KKE0fir8S6syvj9mMfCKhjp5rFX3yiaWPiweFxQ2bRkCrDGiJOxzO3SAzviLMlcz8JcAJLEHku3Osk6HSssf/h5RY95RsRFFrWAR9z9KbOzLp+si7/O4aLG6qz52SfjK8lLV/JObGukswRO3ZVIXXv5xrQItW+Anu6ZMHIK1jqqwjeZ6TUXu+SE11TYIAgutb5QcdXJkq8JzZNHbFV6fjv7nktuPLFInU6ka/2YeoS/PkvGu+cf2Z+mdBeOATESrC74ggn8JwmMmqwYHvlzK+OUO+/HfLe6oAuUks1Jcr1od6yyUzeS13x3orXEH+sDws/Igv1si/jh2AYCEbhlBkIHpTHu6liDf9UGSHvP/h8rtLVvnRsRwBeLGkmX3vSyFzKfyeZ4jX+ESp09DLA2dGPks/NU+zUNQuQQ44XuSVD9UxQDV86FQuo/e+5nP3yD27ez4Wl31FivU8ZuRBXxvwjbuR+5ZlSd6O1jeVqRcuBoCFdeDhsr9pn4MFwpZvlezPe3r8S/+NFmEJi+i+i9fzLjhDIfU4wK5YtE0F+g=
  - secure: 0Iho5mKEblXz4FoYhgN85teACCDWth/CQS4oHudhEep/g4FKGg/29VupA0J7puQx9T9vQy0u5ZX7UpDlge4WGaR+eMQtiirEm57tD4Jdlw/vbg2jMvCsENwd2Ki35d0uKxWDOHPEWVhsczRquCw1REjshaMBtj5eomTJptoyH55vCrvAmiR/4oJ9ZfAIMP2FDo36nZvy1HMISbm1rJRUX6SDhOrgNkyTAWCSDHbvmyBa1BK/IU8DvHIjvgWAezmn8QrpLV9kuZiO5V2SSWTe9oR6QyaT6qbg8GaLi/ik7fXaWW2a81Ty/leUiz/a8Q0K41bVP+UVD5v7FXTfY/9AOAAEM8W0BArdPUwNm2P/jFuGXPI0r6Fk+vvCo3rb5iY9p9+/t5Ot5qykgvd79/4UkV9Q68gzi0vL+92EMQvGjbWeGNt2Su1Jvt4S4N8hVqOqZ1C3c382xOVM0fgsR+iPb06/kd+8uzZdssedazMp6N0hbP5EsBJ5OL6agUlZnFT3JGdVv2QRvpN46qCgPCCDMQ+CtMJCMufiwE/06TujA9LcZM4/ZkyTOIXBn08chz7FjjpCD2HdJvsJsDNzvoUuns6P6wxH1cCOrf08do4aZY5OXacSAhmDRxneeVx8St1Gy7jS4eRokrawUk8W5Qn8cs84lSzk7yCfo0Ze391UNtA=
  - secure: Wm2LBCOftS2lSOUB7zMHXLC1e5fJyzi2Bo0dhcP63fzJGAvdQUiebkHBeRcH1q2IG9J9QIfszLfN6bX/effqpu7huiwk0HN0PFNKAyE+QLpig83/ipXFdx3aGlhGOfbWqKxuwhsw8LZ/4kbj9jQcSd0GIJdpbaeglR5DBSFiVXe/SNLTNTHrQ4mGz+M0VUF15Q5mniI51ZdoMmEamhDz//AQQ23Ne+FFAPCOcs6mw0I0dm7YygHG3ekkQJEo+IIhOzl4N89yfaloaiKQFkIeiWWV3pXVlWCB9kYFqGbarY2RWfqWDNBU+qxm38oiHP6W3tyPiClSMtF7Pf4MfE9JlM4eag39VmiDuw5IwDertSbXyv1hgT4ssnqSsiki9S0t1V74HUqISenBfJeoSkHHUyZb7V+XQnzpq42BikID1UYj/AdzALHRpgzsPvWvPGX5ix7VCBqUOV1TV6WXGGrqyAhG1Xv/IGTCdjnaO58F4tu+3DMU2sJQCMX5qKGFLvlbVJ10j57MzeFgudSOEdMmE4rqfF6rEAEZu1TBvG73bo957EUZjWmC3Jz81ZOOW84riToHbMkMTA/yHHRowSAOTJwbBDYXWEJQA/lKkqSSbP1MnqwfxnFwVXZ2ttdoVnvoJQklcP4woCVdPA1q9+dtxBXhBeV0Et99+MhMtBBKAXc=
before_install:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$password"
  -in id_rsa.enc -out deploy_key -d; fi
